### ISSUE TITLE
Scope out analytics options

### ISSUE THREAD

**Issue by VulpesFerrilata** [Dorset-Council-UK/GIFramework-Maps#103]
We're currently using [Cloudflare](https://www.cloudflare.com/en-gb/) for analytics.

Is there a way to allow developers to choose their own analytics platform(s), and to integrate this with the admin console? This would also involve looking at cookies and how we tell users about cookies.

Options for analytics could include:

- Google Analytics
- Microsoft Clarity
- Cloudflare

**Comment by weolo** [comment]
Google Analytics and Microsoft Clarity and awesome solutions. And doesn't the council already use these?

I do know that central government uses Google Analytics so it would make a lot of sense to go with that. They recently upgraded to GA4 and they even documented their lessons learned on GDS https://gds.blog.gov.uk/2023/03/27/sharing-data-and-lessons-from-our-google-analytics-4-upgrade/

**Comment by RobQuincey** [comment]
@weolo When I initially implemented this using Cloudflare Web Analytics, the first concern was to be privacy first. GA and Clarity are very good, but they are also incredibly invasive, collecting way more data than we actually needed or were able to do anything with. They also required cookie prompts, whereas Cloudflare does not as its a cookie-less implementation. This meant we could avoid the dreaded 'agree to cookies' prompt.

Ideally this should all be configurable, so admins can choose from a number of providers based on their needs.
