### ISSUE TITLE
Close the search results by clicking away

### ISSUE THREAD

**Issue by VulpesFerrilata** [Dorset-Council-UK/GIFramework-Maps#104]
When you're searching, you can usually close the search results by clicking on the 'X' button in the top-right corner. 

![image](https://github.com/Dorset-Council-UK/GIFramework-Maps/assets/114388582/b1798df0-da47-4362-bf6b-2a022ac44d73)

This button disappears however if you have a long list of search results and have scrolled down through them:

![image](https://github.com/Dorset-Council-UK/GIFramework-Maps/assets/114388582/0b33a4ca-1913-4d9d-8c04-8a93c8189a37)

One solution would be to make the 'X' button stick in position as the results are being scrolled. Another solution would be to make the search results box close if a user clicks anywhere outside the results, such as clicking on the map. We could even try doing both of these.

**Comment by weolo** [comment]
Using a Bootstrap Modal may make more sense for what you need. They come with sections for header, body, and footer. So the title, close button, and any action buttons would always be visible. Possible the scrollable modal so you can scroll the body content https://getbootstrap.com/docs/5.3/components/modal/

But if you do still want to use Bootstrap cards for this you could define header, body, and footer sections with those yourself https://getbootstrap.com/docs/5.3/components/card/#header-and-footer
But as these don't immediately have a scrollable area for the body you would need to put in your own solution to cope with that.
