### ISSUE TITLE
OpenStreetMap as a basemap

### ISSUE THREAD

**Issue by VulpesFerrilata** [Dorset-Council-UK/GIFramework-Maps#107]
We've had a few bits of feedback asking for OpenStreetMap to be included in the basemaps list. 

It was available in the previous version, is there a reason why we haven't included it as of yet?

**Comment by RobQuincey** [comment]
Wasn't included as their tile usage policy for their tileserver requests that you don't use it for anything heavy. It is included if you do a fresh build and seed the database from the startup code (https://github.com/Dorset-Council-UK/GIFramework-Maps/blob/1f2a561a75559b7c4112dcad427fea4f2a755602/GIFrameworkMaps.Web/Startup.cs#L280). There is no technical reason as it is a standard XYZ tile service, just not added in our instance as we had access to OS Maps

**Comment by paul-dorsetcouncil** [comment]
Probably best to leave it out for now I think @VulpesFerrilata as I'd forgotten that but as Rob says they did raise some issues. I think the plan (in the fullness of time) is to be able to host it internally as this is what you are meant to do but it is just not a high enough priority for us right now with all the other work we are doing. Especially given that we have the open OS stack.

**Comment by VulpesFerrilata** [comment]
Thank you both - I'll close off this issue for now then :)
