### ISSUE TITLE
Regression - Basemap picker text not visible

### ISSUE THREAD

**Issue by RobQuincey** [Dorset-Council-UK/GIFramework-Maps#119]
The names of the basemaps in the basemap picker are no longer visible.

Likely due to a change in the Bootstrap CSS overriding the original colour.

![image](https://github.com/Dorset-Council-UK/GIFramework-Maps/assets/28754239/8aa16be6-6a97-41a3-917e-d286693f7300)

Can be fixed by specifying the colour on the `.giframeworkMap aside#sidebar-container .sidebar-panels .card.basemaps-selector a` rule 

`color: var(--primary-color);`

**Comment by VulpesFerrilata** [comment]
Ahhh I didn't notice this, despite testing everything... I'll fix it tomorrow, thank you :)
