### ISSUE TITLE
Improve developing documentation

### ISSUE THREAD

**Issue by totpero** [Dorset-Council-UK/GIFramework-Maps#133]
Hi,
I cloned this repo because I want to contribute, but when I try to run using visual studio, it wasn't so easy.

If someone want to run this project it need to do some reverse engineering. 

You need to configure this solution to run on local environment.  

Now in appsettings.json is missing the  postgres database connection configuration:

```
 "ConnectionStrings": {
   "GIFrameworkMaps": "Server=localhost; Port=5432; Database=GIFrameworkMaps;User Id=postgres; Password=postgres3"
 },
```
All the Management Controllers use:
`[Authorize(Roles = "GIFWAdmin")]`
**But your Authentication and Authorization is configure with your Azure Identity**

Or write some documentation how to start this project using visual studio.

You do great job with this project, but make it easy accessible to other developer to contribute.
👍

**Comment by paul-dorsetcouncil** [comment]
Hi, 
I'm just checking through the logs but it looks like a number of services were not running for a period last night at the council. I think it is back online now. We will come back on the main point shortly but I thought I'd acknowledge the issue with the live service straight away. Thank you for reporting. 

> P.S.: Your live link don't work : https://gi.dorsetcouncil.gov.uk/dorsetexplorer

**Comment by paul-dorsetcouncil** [comment]
So having looked at our documentation on GitHub I see the bit you are referring to is marked as a TODO so as you say the instructions are not entirely there yet. We will try to get some more documentation up when we have time but as you will imagine we do struggle a bit for time with this project as we have other projects as well. The basic plan is to run a code sprint at some point soon where the first part of the day will be focused on helping people to clone and run the application locally. 

We hope this will be a really useful event in terms of helping to grow an open source community but as you will imagine it will also be really helpful for improving the documentation you are suggesting. 

That said, we do have some internal documentation on the bit you mention about configuring the local Postgres database so we will try to add that as soon as we can to help you run it. 

You are also correct that our current model uses Microsoft authentication using OpenID Connect so currently we can only really document how you would achieve this using the same method. You are not limited to Microsoft as other providers such as Google support OpenID Connect but you would need some form of authentication tool with the ability to assign a role. 

Sorry you attempt was not so successful last night and thank you for reaching out to us. We will try to get you some better help guidance over the coming week.

**Comment by VulpesFerrilata** [comment]
Hi @totpero 👋

Thanks for reaching out. I'll put together some detailed guidance on how to get this running on your local environment. I'm not around next week, but I'll write some guidance during the week after when I'm back (3 July onwards). 

In the meantime, feel free to ask any specific questions here and we'll see what we can do 😊

**Comment by totpero** [comment]
Hi @paul-dorsetcouncil and @VulpesFerrilata 
Thanks for your responses,
I start this project by add my connection string and run the migration and after I comment the Authorize attribute to access the administration part. I think that will be much easy if you adapt this code to run on local with minimal configurations. 

From Romania I can't access this URL. I get connection timed out.

You are doing great job with this project. 👍 

> Hi, I'm just checking through the logs but it looks like a number of services were not running for a period last night at the council. I think it is back online now. We will come back on the main point shortly but I thought I'd acknowledge the issue with the live service straight away. Thank you for reporting.
> 
> > P.S.: Your live link don't work : https://gi.dorsetcouncil.gov.uk/dorsetexplorer

**Comment by paul-dorsetcouncil** [comment]
> From Romania I can't access this URL. I get connection timed out.

Ah I see. As a council with a defined remit within the UK I believe we do have policies that prevent access from most countries outside the UK. Sorry about that but hopefully, over time, more people will join this project and we will have other examples of the application running that are accessible.

**Comment by RobQuincey** [comment]
@totpero I do have a dev environment running that you might be able to look at

https://giframeworkmaps.quincey.dev/

It is really only for my dev purposes, so it only has a few basemaps, one or two layers and a couple of basic searches available, and I can't guarantee it will be there forever/always up to date, but might give you an idea of the basics.
