### ISSUE TITLE
Add friendly name to search definitions

### ISSUE THREAD

**Issue by RobQuincey-DC** [Dorset-Council-UK/GIFramework-Maps#141]
Currently, search definitions have:

Name - A name for administrators
Title - The name that appears in the search results

The 'name' should be the name used in the management console for administrators to easily see what something is. It may contain technical information irrelevant to the end user. As a current example, DorsetExplorer contains search definitions called 'GeoAPI - Addresses by Postcode' and 'GeoServer Parishes'. The first part of those is irrelevant to the user but useful to the administrator.

Title does not really fit the bill, as this is the title as rendered in the search results window. For example, the two Address searches in DorsetExplorer (by postcode and by name) both have the same title, as we want it to just say 'Addresses' in the search field.

I propose either:

- Adding a new column for 'Friendly name' which will appear in the users UI instead of 'Name' or
- Changing the 'Name' to be a user friendly name instead of for administrators

Option 2 is simpler but administrators will have less information at a glance regarding what the search definition is, and there could be name collisions if the system requires two similar search definitions with different implementations

**Comment by paul-dorsetcouncil** [comment]
True, but in theory we can also see the source details as admin so we would know it was GeoAPI anyway. I'm happy with whichever you choose but think going with option 2 is probably best practice in that situation.
