### ISSUE TITLE
Include hash parameters in login redirection URL

### ISSUE THREAD

**Issue by RobQuincey-DC** [Dorset-Council-UK/GIFramework-Maps#144]
When logging in, the return URL does not include the hash parameters, so the users map setup is lost

**Comment by paul-dorsetcouncil** [comment]
With old DE I got around this by storing the full URL in a database but I don't like the solution. I was hoping that using the full .NET core standard would be better but I guess not. This however reminds me that I was going to mention we need to add a retention policy for permalinks as well. I don't think we want to keep them indefinitely so do you have a default length? I'd say a couple of weeks or a month should be the maximum if not logged in and then we can provide options for logged in users.
