### ISSUE TITLE
Add datatables in the admin back-end

### ISSUE THREAD

**Issue by VulpesFerrilata** [Dorset-Council-UK/GIFramework-Maps#153]
Add datatables functionality to the admin back-end, as some of the tables are starting to get large and hard to manage.

Use simple datatables to avoid using jquery: https://github.com/fiduswriter/simple-datatables

**Comment by paul-dorsetcouncil** [comment]
Is it on a test version anywhere? Code looks fine but I couldn't see the actual functionality on the layers list on gi-staging?
