### ISSUE TITLE
Add optional legend to prints/PDF exports

### ISSUE THREAD

**Issue by VulpesFerrilata** [Dorset-Council-UK/GIFramework-Maps#18]
We would like users to be able to include a legend when exporting to a PDF as an optional checkbox.

A legend should not be editable, it would just be as it comes and include items from the layers that have been turned on (such as addresses or rights of way). It would be best as just a panel on the side of the map to avoid issues of placement over map objects.

**Comment by RobQuincey-DC** [comment]
Closed #165
