### ISSUE TITLE
Viewport extends outside of visible window in mobile browsers

### ISSUE THREAD

**Issue by VulpesFerrilata** [Dorset-Council-UK/GIFramework-Maps#24]
**Steps to reproduce issue**

Open on a mobile browser (tested with Edge). Testing using the devtools emulators doesn't work, it needs to be a real device.

The bottom 'chrome' of the browser (e.g. forward/back links, menu etc.) hides the attribution/coordinates/scalebar. It also makes the page 'scrollable' which it should not be. 

![image](https://user-images.githubusercontent.com/114388582/214841664-ba95f788-1a89-48f9-bd13-a704c933177f.png)

There is a potential workaround using a vendor specific prefix here:
[CSS fix for 100vh in mobile WebKit - Matt Smith (allthingssmitty.com)](https://allthingssmitty.com/2020/05/11/css-fix-for-100vh-in-mobile-webkit/)

Adding `min-height: -webkit-fill-available;` to the giframeworkMap class seems to mitigate the issue.

Other mobile browsers need to be tested too.

**Comment by RobQuincey-DC** [comment]
This was fixed a while ago, only remaining issue is #38
