### ISSUE TITLE
Add metadata link to layer infoclicks

### ISSUE THREAD

**Issue by VulpesFerrilata** [Dorset-Council-UK/GIFramework-Maps#263]
Most layers have a link to metadata which can be accessed by clicking on the info button next to each layer. This gives helpful information about a layer including a simple description of what it shows and any attribution details.
![image](https://github.com/Dorset-Council-UK/GIFramework-Maps/assets/114388582/02353209-3108-4980-a298-9d4bcfc36ccf)

It would be useful to include a link to the metadata on the info click modal as well. This would save users from having to remember which layer they are looking at and would be especially helpful on embedded maps which already have layers switched on.
![image](https://github.com/Dorset-Council-UK/GIFramework-Maps/assets/114388582/36be30cb-6b62-4112-9c33-398e41dae2f6)

**Comment by paul-dorsetcouncil** [comment]
I like this suggestion as I think a lot of users never find their way to the metadata. This may help and I guess it could be something we can toggle on an off layer by layer if we find it is cluttering the results. There are definitely some layers you would want to enforce it for whilst I guess some might be less clear cut.
