### ISSUE TITLE
Tidy up Program.cs

### ISSUE THREAD

**Issue by RobQuincey-DC** [Dorset-Council-UK/GIFramework-Maps#283]
`Program.cs` has grown over time and is now quite messy. It could do with a general tidy up, splitting things off and organising them a bit better.

**Comment by Omared-1** [comment]
Hi 

I’ve completed the tidy up the Program.cs file as discussed in this issue. Here’s a summary of what was done:

Refactored Program.cs:

Moved Azure Key Vault configuration to a separate method (ConfigureKeyVault).
Moved service configurations to another method (ConfigureServices).
Added comments to explain each section of the code to improve readability and maintainability.
These changes should make the file more organized and easier to manage. Please review the updates and let me know if there are any further changes needed.

Thank you!
