### ISSUE TITLE
Add layer specific disclaimers

### ISSUE THREAD

**Issue by paul-dorsetcouncil** [Dorset-Council-UK/GIFramework-Maps#303]
**Describe the solution you'd like**
We have had requests to add a disclaimer to a specific layer. 

We could create an option to trigger a layer specific disclaimer and display this one of two ways:

1.  We would just display them in the version disclaimer and make the user accept them for each layer
2.  We could make them appear when the user switches on the layer for the first time. 

There are a number of considerations but most important will be balancing the user experience against the need to ensure users understand the datasets they are seeing. Too much emphasis on the disclaimer is likely to reduce the user experience but too little could result in misuse of datasets and potential consequences for the user.  

**Describe alternatives you've considered**
If you add this to the description of the layer then disclaimer will be visible if you click the 'i' tool in the layers list but if the user doesn't do this they may easily miss the disclaimer.

**Comment by RobQuincey-DC** [comment]
Closed via #329
