### ISSUE TITLE
Some js links using `href="#"` override the URL when clicked

### ISSUE THREAD

**Issue by RobQuincey-DC** [Dorset-Council-UK/GIFramework-Maps#306]
Some JS links in the app with `href="#"` override the URL (which acts as the map permalink) when clicked. This is likely because the script which does whatever it needs to do does not call `e.preventDefault()` to prevent the URL from updating to `#`

**Steps to reproduce**
- Click an affected link  (e.g. 'Collapse all' in the layer control)
- The URL in the address bar updates to `https://[domain]/#`

**Affected links**
This list is not exhaustive. If you find any others, add it to the list.
- 'Collapse all' in the layer control
- Cookie preference in help menu
- Info click list results (although it seems to refresh immediately after)
    - This is the list that comes up when you click a point on the map that has multiple data items in it

**Comment by Matt-W-DC** [comment]
Fixed this issue for 'collapse all' in the layer control and info click list results in linked branch 'bugfix-link-overrides-URL-306' by adding e.preventDefault().

**Comment by RobQuincey-DC** [comment]
@Matt-W-DC This is great, thanks. Did you manage to find the one for the Cookie control. Its a funny one to test locally as you need to add some config settings for it to actually appear. I think the code itself is in app.ts line 55
