### ISSUE TITLE
Convert settings to use IOptions

### ISSUE THREAD

**Issue by RobQuincey-DC** [Dorset-Council-UK/GIFramework-Maps#323]
Convert string based IConfiguration to use IOptions. This will make the configuration options safer to use.

**Comment by ChumboMJ** [comment]
Hey, I am interested in this as a first issue, I've got the project pulled down and running locally so I should be able to work on this today!

**Comment by RobQuincey-DC** [comment]
@ChumboMJ you are more than welcome to work on this as its unlikely any of the core team will have time to do it in the near future. We will happily accept a pull request. If you have any questions just ask.

**Comment by ChumboMJ** [comment]
@RobQuincey-DC Hey Rob, I think I am pretty much done on this, but I do have one quick question - are you able to show me what they key name for the Google Api is stored as in the Key Vault? I made the assumption that it will be stored under "ApiKeys--Google--MapsApiKey", which maps over to the Options object I have created perfectly.

All of the values in the appsettings.json are mapping over to my Options object as well, so I am just looking to confirm my code is working for the Azure values before I submit a pull.

Thanks!
-Tim

**Comment by RobQuincey-DC** [comment]
@ChumboMJ That's correct, this follows the convention for naming hierarchical values from appSettings in KeyVault.

From the Microsoft Docs - https://learn.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-9.0#secret-storage-in-the-production-environment-with-azure-key-vault

> Azure Key Vault secret names are limited to alphanumeric characters and dashes. Hierarchical values (configuration sections) use -- (two dashes) as a delimiter, as colons aren't allowed in Key Vault secret names. Colons delimit a section from a subkey in [ASP.NET Core configuration](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-9.0). The two-dash sequence is replaced with a colon when the secrets are loaded into the app's configuration.

So `ApiKeys--Google--MapsApiKey` is the equivalent of this in appSettings

```
{
"ApiKeys":{
    "Google":{
        "MapsApiKey": "[keygoeshere]"
    }
}
```

Thanks for your work on this.
