### ISSUE TITLE
GPS integration

### ISSUE THREAD

**Issue by RobQuincey-DC** [Dorset-Council-UK/GIFramework-Maps#40]
**Is your feature request related to a problem? Please describe.**
Users should be able to use the GPS functionality of their device to get their current location on the map and track their position

**Describe the solution you'd like**
A standard GPS button that allows users to either get their current location as a one off, or start tracking their location, preferably drawing a track on the map and, when finished, giving the user the option to download it.

**Additional context**
DorsetExplorer 3 currently does this
![image](https://user-images.githubusercontent.com/109682469/215436681-33a203fa-67c9-4283-bd59-d19982ddc2c1.png)

**Comment by RobQuincey** [comment]
I'd like to take a gander at this next week. Probably easier for me from a home machine as well, as I think yours have geolocation blocked ☹️

**Comment by paul-dorsetcouncil** [comment]
Sounds good. Thanks for looking at that as it will be really useful I think. Definitely annoying that it is blocked on DC devices but I guess we will have to trial the QField route.
