### ISSUE TITLE
Compilation outside of DC

### ISSUE THREAD

**Issue by paulwittle** [Dorset-Council-UK/GIFramework-Maps#64]
**Describe the bug**
When cloning and running it outside of the DC we have yet to provide details of how to configure the secrets. I was able to get it to connect to a blank database schema, in fact two, giframeworkmaps and identity however it then came up with:

>  42P01: relation "identity.AspNetUsers" does not exist

**To Reproduce**
Clone and run Update-Database

**Expected behavior**
This is expected as we are still setting up open development but leaving bug report as note to self to investigate further.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows

**Smartphone (please complete the following information):**
 N/A

**Additional context**
No other comments

**Comment by paul-dorsetcouncil** [comment]
I will try to test this later this week so we can sign off and close

**Comment by paulwittle** [comment]
I can confirm that I'm now able to build this on my home PC so this issue is resolved.
