### ISSUE TITLE
Duplicate layers in a single version cause issues

### ISSUE THREAD

**Issue by RobQuincey-DC** [Dorset-Council-UK/GIFramework-Maps#77]
**Describe the bug**
When the same layer is added to the same version multiple times (by appearing in different categories), the UI becomes inconsistent. Clicking on the duplicate can result in the 'other' checkbox for that layer to be checked, which is very jarring.

**To Reproduce**
1. Add a layer to multiple categories
2. Add those categories to a version
3. Turn on a layer in the category

**Expected behavior**
The duplicates should either
- Work together to switch on and off. This has the advantage of allowing layers to appear in multiple categories, but this itself is confusing and should ideally be avoided, or
- Hide the duplicates and preferably warn the admins that duplicates have been detected

**Comment by paul-dorsetcouncil** [comment]
Might need to look at how we have dealt with the layers. My gut feel is that layers should only be defined once but have the option of multiple categories. Where more than one category is present in a version the admin user selects the one they want it displayed in. 

I would also then suggest that we add some logic to basically block the user from selecting no (or multiple) categories and this should resolve the issue. 

I'll try to remember to mock something up but I definitely want to avoid the way we did it in the old DE.

**Comment by RobQuincey-DC** [comment]
Closing as the bug itself is now mitigated in #183 
Will open a new issue to enhance the administration interface to warn users of this issue and give them a chance to remedy it using the layer customisations feature
