### ISSUE TITLE
Metres to Yard conversion appears to be wrong

### ISSUE THREAD

**Issue by RobQuincey** [Dorset-Council-UK/GIFramework-Maps#97]
**Describe the bug**
When viewing a line measurement for a short line, the 'imperial' measurement appears to be wrong

**To Reproduce**
Steps to reproduce the behaviour:
1. Draw a relatively short line measurement
2. Finish the line, disable the tool and then click the line to reveal the alternative measurement.

**Screenshots**
![image](https://user-images.githubusercontent.com/28754239/225029130-9ad4b905-9b9c-4a6e-af5e-aa9aa6549bd5.png)

**Comment by paul-dorsetcouncil** [comment]
Yep, that does appear wrong...oops

**Comment by RobQuincey** [comment]
I can't tell you all what to do anymore, but this seems an ideal issue for @VulpesFerrilata to look at 🙂
